"""Train simple tree-based regressors to predict each simulator output
from the input features, using the synthetic dataset from
`simulation.generate_dataset` (optionally combined with real
measurements via `ml.dataset.assemble_training_dataset`).

For each target, three candidate regressors are trained and the one
with the lowest test-set RMSE is kept. Because most training rows are
themselves generated by the deterministic physics model in
`models.simulator`, these models mostly learn to approximate that
physics model rather than real membrane behavior — see
docs/assumptions.md ("ML trained on synthetic data inherits
physics-model assumptions"). Rows sourced from real experimental data
(see ml.dataset) help pull the fit toward reality where they exist.

Note that FEATURES below includes several inputs (e.g. pore_size_nm,
porosity, water_turbidity_NTU, op_crossflow_velocity_m_s) that the
*simple* physics model never actually uses when generating targets
(see models/membrane.py for the full breakdown of which fields are
"live" for `run_simulation` — most of them ARE used by
`run_detailed_simulation`). Including them here is intentional and
mostly harmless — a well-trained tree model should assign near-zero
importance to any feature the generating model ignored — but it means
feature importances say more about "did the input correlate with
whichever model generated the training targets" than about universal
membrane science. Use `ml.explain` to check this directly.
"""

from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

from .features import engineer_features, available_engineered_columns

TARGETS = ["flux_LMH","rejection_percent","flux_decline_percent","permeate_mg_L","energy_kWh_m3","feasibility_score"]
FEATURES = ["thickness_um","permeability_LMH_bar","pore_size_nm","MWCO","porosity","surface_charge",
          "hydrophilicity","baseline_rejection_percent","water_feed_concentration_mg_L",
          "water_turbidity_NTU","water_TDS_mg_L","water_pH","water_temperature_C",
          "op_TMP_bar","op_feed_flow_L_min","op_crossflow_velocity_m_s","op_recovery_percent",
          "op_operating_time_hr"]


def feature_list_for(df, use_engineered_features=False):
    """The exact ordered feature-column list `train_models` will use
    for `df`: FEATURES, or FEATURES + whichever ENGINEERED_FEATURES can
    actually be derived from `df`'s columns if
    `use_engineered_features=True`."""
    if not use_engineered_features:
        return list(FEATURES)
    return list(FEATURES) + available_engineered_columns(df)


def train_models(df, seed=42, use_engineered_features=True):
    """Train one best-of-three regressor per target in TARGETS.

    Returns (models, metrics, feature_list):
      models       -- dict of {target_name: fitted_estimator}
      metrics      -- list of dicts, one per target, with the chosen
                       model's name and test-set MAE/RMSE/R2
      feature_list -- the exact ordered list of feature column names
                       used to fit every model (needed later to line up
                       columns correctly at prediction time — see
                       ml.model_registry / ml.predict)

    Rows with a NaN target are dropped (a real-measurement row that
    only reports flux, for example, contributes to fitting the flux
    model but not the others). Missing feature values are imputed with
    that feature's column median.
    """
    work = engineer_features(df) if use_engineered_features else df
    feature_list = feature_list_for(df, use_engineered_features)
    X_full = work[feature_list].fillna(work[feature_list].median())

    models, metrics = [], []
    for target in TARGETS:
        mask = work[target].notna()
        X = X_full[mask]
        y = work.loc[mask, target]
        if len(X) < 10:
            raise ValueError(f"Not enough labeled rows ({len(X)}) to train a model for target '{target}'.")
        Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=.2, random_state=seed)
        candidates = [
            ("Random Forest", RandomForestRegressor(n_estimators=150, random_state=seed, n_jobs=-1)),
            ("Extra Trees", ExtraTreesRegressor(n_estimators=150, random_state=seed, n_jobs=-1)),
            ("Gradient Boosting", GradientBoostingRegressor(random_state=seed)),
        ]
        best = None
        best_rmse = float("inf")
        for name, model in candidates:
            model.fit(Xtr, ytr)
            pred = model.predict(Xte)
            rmse = float(np.sqrt(mean_squared_error(yte, pred)))
            if rmse < best_rmse:
                best_rmse = rmse
                best = (name, model, pred)
        name, model, pred = best
        metrics.append({"target": target, "model": name, "MAE": mean_absolute_error(yte, pred),
                        "RMSE": best_rmse, "R2": r2_score(yte, pred), "n_train": len(Xtr), "n_test": len(Xte)})
        models.append((target, model))
    return dict(models), metrics, feature_list
